### ISSUE TITLE
GTuner crash when I want to drag'n'drop a script to a memory slot

### ISSUE THREAD

**Issue by omasseau** [J2Kbr/GtunerIV#97]
Today I updated GTuner to the latest version: 0.93.1.1271

When I try to drag'n'drop a gpc script to a memory slot, Windows says the program has crashed and has to be closed.

As a consequence, I cannot upload script to my Titan Two anymore...

Windows version: Windows 10 64 bits.

**Comment by omasseau** [comment]
Actually I just noticed that GTuner did not update to the latest version (0.95.1.1336).

Each time I click on 'Donwload and update', GTuner restart but I'm still in 0.93

**Comment by omasseau** [comment]
Finally fixed  by manually downloading version 0.95.1.1336.

After downloading it and extracting it in the same path as before I got an error saying Qt could not be found with an invalid path displayed in the error message.

My path of installation contained accents (E:/Téléchargement/Jeux/GTuner)  which were replaced by other characters in the error message (can not remember which exactly).

Finally I moved the GTuner folder in a path containing no accents and the problem was solved.

So it seems GTuner has problem with path containing accents ;)

**Comment by PablosScripts** [comment]
This still seems like a bug. I think you should reactivate it.

**Comment by PablosScripts** [comment]
I started getting this when I had too many accessories connected. To fix this I disconnected a few things like my mouse and keyboard and it began working again. I think this is a power related problem.

**Comment by J2Kbr** [comment]
@omasseau Soon Gtuner IV 0.100B will be released, please try update your current version after the new version gets released and reopen this GitHub issue in case of still facing problems with the automatic update command.
